source:
  Twitter:
    _icon_: "https://raw.githubusercontent.com/lalitpagaria/obsei/master/images/logos/twitter.png"
    source:
      _target_: obsei.source.twitter_source.TwitterSource
    config:
      _target_: obsei.source.twitter_source.TwitterSourceConfig
      keywords:
        - "twitter issue"
      lookup_period: "1h"
      max_tweets: 5
      credential:
        _target_: obsei.source.twitter_source.TwitterCredentials
        consumer_key: ''
        consumer_secret: ''
  Appstore Scrapper:
    _icon_: "https://raw.githubusercontent.com/lalitpagaria/obsei/master/images/logos/appstore.png"
    source:
      _target_: obsei.source.appstore_scrapper.AppStoreScrapperSource
    config:
      _target_: obsei.source.appstore_scrapper.AppStoreScrapperConfig
      countries:
        - "us"
      app_id: "310633997"
      lookup_period: "1h"

sink:
  Slack:
    _icon_: "https://raw.githubusercontent.com/lalitpagaria/obsei/master/images/logos/slack.png"
    sink:
      _target_: obsei.sink.slack_sink.SlackSink
    config:
      _target_: obsei.sink.slack_sink.SlackSinkConfig
      slack_token: ''
      channel_id: ''


analyzer:
  Sentiment:
    _icon_: "https://raw.githubusercontent.com/lalitpagaria/obsei/master/images/logos/sentiment.png"
    Vader:
      analyzer:
        _target_: obsei.analyzer.sentiment_analyzer.VaderSentimentAnalyzer
    Transformer:
      config:
        _target_: obsei.analyzer.sentiment_analyzer.TransformersSentimentAnalyzerConfig
        labels:
          - "positive"
          - "negative"
        multi_class_classification: false
      analyzer:
        _target_: obsei.analyzer.sentiment_analyzer.TransformersSentimentAnalyzer
  Classification:
    _icon_: "https://raw.githubusercontent.com/lalitpagaria/obsei/master/images/logos/classification.png"
    Transformer:
      config:
        _target_: obsei.analyzer.classification_analyzer.ClassificationAnalyzerConfig
        labels:
          - "service"
          - "content"
          - "interface"
        use_sentiment_model: true
      analyzer:
        _target_: obsei.analyzer.classification_analyzer.ZeroShotClassificationAnalyzer
        model_name_or_path: "joeddav/bart-large-mnli-yahoo-answers"
        initialize_model: true
