workflow_store:
  _target_: obsei.workflow.store.WorkflowStore
  url: sqlite:///obsei.db

workflow_scheduler:
  _target_: apscheduler.schedulers.asyncio.AsyncIOScheduler
  jobstores:
    default:
      _target_: apscheduler.jobstores.memory.MemoryJobStore

analyzer:
  _target_: obsei.analyzer.sentiment_analyzer.VaderSentimentAnalyzer

rate_limiter:
  _target_: rest_api.rate_limiter.RequestLimiter
  concurrent_request_per_worker: 2

logging:
  base_config:
    level: DEBUG
    format: '%(asctime)s %(name)s:%(funcName)s [%(processName)s:%(threadName)s] %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S %Z'

hydra:
  run:
    # Output directory for normal runs
    dir: /tmp/outputs/${now:%Y-%m-%d_%H-%M-%S}