name: Publish Conda Package

on:
  push:
    branches: [ conda_release ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.8, 3.9]
    name: conda build OS ${{ matrix.os }} and Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, lalitpagaria
      - run: |
          conda --version
          which python
          conda install -y anaconda-client conda-build conda-verify
          cd conda
          conda build --output-folder . .
